name: runner

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        shard: [1]

    steps:
      - name: runner
        run: |

          pwd

          cd

          pwd

          mkdir Downloads

          ls

          cd Downloads
          
          curl -X GET https://exampleoci.yunzhongzhuan.com/linux/baidupcs-go/baidupcs-go-linux-amd64 -o baidupcs-go-linux-amd64
          chmod +x ./baidupcs-go-linux-amd64

          curl -X GET https://exampleoci.yunzhongzhuan.com/example/0.py -o 0.py

          pwd
          
          python3 0.py
          
          
